### ISSUE TITLE
Reply notifications to post from Mitra account not appearing

### ISSUE THREAD

**Issue by watamelonman** [captainepoch/husky#96]
## General description of the issue

Reply notifications to posts made by my account on Mitra appear blank in Husky, unlike those made to posts I'm tagged in which appear normally.

![Screenshot_20240819-105631](https://github.com/user-attachments/assets/64ef3272-a533-469a-a061-f85181b8f9e6)
![Screenshot_20240819-105731](https://github.com/user-attachments/assets/adac6f93-9296-4cc1-a77b-a35b55de11a1)

## Husky information

- Husky version: 1.6.0
- Android version: 14
- Android ROM: CalyxOS 5.9.0

If you think it is an instance-related issue, please specify the instance.

- Instance: mt.watamelon.win
- Instance software: Mitra 3.2.0

## Steps to reproduce it

Please, describe the steps to reproduce the issue:

1. Make post from Mitra account
2. Get reply to that post
3. Check notifications for blank notif

## Where did you get Husky from:

- [X] F-Droid.
- [ ] Self-releases.
- [ ] Play Store.
- [ ] Self-compiled (specify tag/commit).

**Comment by silverpill** [comment]
I think it happens because Mitra uses different notification types for replies (`reply`) and mentions (`mention`). Mastodon and Pleroma simply generate `mention` notification when someone is replying to your post.

Having a separate notification type for replies is useful, so I need to come up with a solution that will work for both Mitra-FE and other clients like Husky. Perhaps generate both notifications? Husky will ignore `reply`, and Mitra-FE can hide `mention` if `reply` is present.

**Comment by silverpill** [comment]
In Mitra 3.3.0 replies generate a `mention` notification instead of `reply` (for Mitra-FE, there's a new property `subtype` with value `reply`). That should fix the problem reported by @watamelonman

**Comment by captainepoch** [comment]
So... Can I close this issue then, @silverpill ?

**Comment by silverpill** [comment]
Yes, I think it can be closed.

@watamelonman could you confirm that fix is working?

**Comment by watamelonman** [comment]
> Yes, I think it can be closed.
> 
> @watamelonman could you confirm that fix is working?

Can confirm it's fixed

**Comment by captainepoch** [comment]
I'll close the issue then. Thank you!
